version: "2.2"

services:
  Firefox:
    image: lileesystems/firefox:4.9.4
    container_name: firefox
    restart: unless-stopped
    env_file:
      - "firefox.env"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/tmp/.pulse:/tmp/.pulse"
      - "paconfig:/etc/pulse"
      - "/var/lib/pulse:/var/lib/pulse"
      - "/run/user/0/pulse:/run/user/0/pulse"
    ports:
      - "5800:5800"
    networks:
      access:
    shm_size: '1gb'
#    entrypoint: /usr/bin/firefox -url https://www.youtube.com
    cap_add: 
      - NET_ADMIN 
      - NET_BIND_SERVICE 
      - NET_BROADCAST
