version: "2.2"
services:
  DiagShell:
    image: lileesystems/sts1k-diagshell:4.9.2
    container_name: diagshell
    privileged: false
    restart: unless-stopped
    mem_limit: 100m
    cpus: 0.1
    env_file:
      - "diagshell.env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      access:
    ports:
      - "2222:22/tcp"
